databases:
  - name: heu_db
    plan: free
    databaseName: heu_1
    user: heu_1
    region: frankfurt

services:
  - type: web
    plan: free
    name: heu_1
    region: frankfurt
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn heu_1.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heu_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4